name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose
      - name: Set env
        run: echo "IMGOPT_VERSION=$(sh ./get_version.sh)" >> $GITHUB_ENV
      - name: Strip and move binary
        run: strip target/release/imgopt && mv target/release/imgopt target/release/imgopt-ubuntu-latest
      - uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: false
          artifacts: "target/release/imgopt"
          tag: ${{ env.IMGOPT_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
